project:
  type: website

website:
  title: "ISSS608 VAA"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "Exercise 1: Grammar of Graphics"
            href: hands-on_ex01.html
          - text: "Exercise 2: Beyond ggplot2 Fundamentals"
            href: hands-on_ex02.html
          - text: "Exercise 3a: Interactive Data Visualisation"
            href: hands-on_ex03a.html

format:
  html:
    theme: litera
    toc: true
    toc-depth: 3
    code-fold: true
    code-summary: "Show the code"
    css: styles.css