project:
  type: website

website:
  title: "ISSS608 VAA"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "Exercise 1: Grammar of Graphics"
            href: hands-on_ex01.html
          - text: "Exercise 2: Beyond ggplot2 Fundamentals"
            href: hands-on_ex02.html
          - text: "Exercise 3a: Interactive Data Visualisation"
            href: hands-on_ex03a.html
          - text: "Exercise 3b: Animated Statistical Graphics"
            href: hands-on_ex03b.html
          - text: "Exercise 4a: Visualising Distribution"
            href: hands-on_ex04a.html
          - text: "Exercise 4b: Visualising Statistical Analysis"
            href: hands-on_ex04b.html
          - text: "Exercise 4c: Visualising Uncertainty"
            href: hands-on_ex04c.html
          - text: "Exercise 4d: Funnel Plots for Fair Comparisons"
            href: hands-on_ex04d.html
          - text: "Exercise 5a: Creating Ternary Plot with R"
            href: hands-on_ex05a.html
          - text: "Exercise 5b: Visual Correlation Analysis"
            href: hands-on_ex05b.html
          - text: "Exercise 5c: Heatmap for Visualising and Analysing Multivariate Data"
            href: hands-on_ex05c.html
          - text: "Exercise 5d: Visual Multivariate Analysis with Parallel Coordinates Plot"
            href: hands-on_ex05d.html
          - text: "Exercise 5e: Treemap Visualisation with R"
            href: hands-on_ex05e.html
          - text: "Hands-on exercise 6a: Modelling, Visualising and Analysing Network Data with R"
            href: hands-on_ex06a.html
          - text: "Hands-on exercise 6b: Visualising and Analysing Text Data with R: tidytext methods"
            href: hands-on_ex06b.html
          - text: "Hands-on Exercise 7: Visualising and Analysing Time-oriented Data"
            href: hands-on_ex07.html
          - text: "Hands-on Exercise 8a: Choropleth Mapping with R"
            href: hands-on_ex08a.html
          - text: "Hands-on Exercise 8b: Visualising Geospatial Point Data"
            href: hands-on_ex08b.html
          - text: "Hands-on Exercise 8c: Analytical Mapping"
            href: hands-on_ex08c.html
            
      - text: "Take-home Exercises"        
        menu:
          - text: "Exercise 1"
            href: take-home_ex01.html
          - text: "Exercise 1 Slides"
            href: take-home_ex01_slides.html
          - text: "Exercise 2"
            href: take-home_ex02.html

format:
  html:
    theme: litera
    toc: true
    toc-depth: 3
    code-fold: true
    code-summary: "Show the code"
    css: styles.css
    embed-resources: true      